global:
  scrape_interval:     1s
  evaluation_interval: 1s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'envoy_client'
    # scrape_interval: 5s
    metrics_path: "/stats/prometheus"
    static_configs:
      - targets: ['envoy-client:9901']

  - job_name: 'envoy_server'
    # scrape_interval: 5s
    metrics_path: "/stats/prometheus"
    static_configs:
      - targets: ['envoy-server:9001']
